channels:
- conda-forge
dependencies:
- python=3.8.18
- pip<=23.3.1
- pip:
  - mlflow==2.8.1
  - cffi==1.16.0
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - lightgbm==4.2.0
  - matplotlib==3.7.4
  - numpy==1.24.4
  - packaging==23.1
  - pandas==2.0.3
  - psutil==5.9.0
  - pyarrow==14.0.1
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
