channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=23.1.2
- pip:
  - mlflow==2.8.1
  - cloudpickle==2.2.1
  - joblib==1.1.1
  - lz4==4.3.2
  - packaging==23.0
  - pathlib==1.0.1
  - psutil==5.9.0
  - pyyaml==6.0
  - scikit-learn==1.3.0
  - scipy==1.10.1
  - threadpoolctl==3.2.0
  - typing-extensions==4.6.3
name: mlflow-env
